// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for the kevy-ffi C ABI (crates/kevy-ffi/include/kevy.h).
///
/// Regenerate with `dart run ffigen --config ffigen.yaml`.
///
class FlutterKevyBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlutterKevyBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlutterKevyBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Open a persistent store rooted at dir (UTF-8, dir_len bytes, no NUL
  /// needed). Replays its log on open. NULL on failure.
  ffi.Pointer<KevyDbHandle> kevy_open(ffi.Pointer<ffi.Uint8> dir, int dir_len) {
    return _kevy_open(dir, dir_len);
  }

  late final _kevy_openPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<KevyDbHandle> Function(ffi.Pointer<ffi.Uint8>, ffi.Size)
        >
      >('kevy_open');
  late final _kevy_open = _kevy_openPtr
      .asFunction<
        ffi.Pointer<KevyDbHandle> Function(ffi.Pointer<ffi.Uint8>, int)
      >();

  /// Open a pure in-memory store — nothing survives the process.
  ffi.Pointer<KevyDbHandle> kevy_open_mem() {
    return _kevy_open_mem();
  }

  late final _kevy_open_memPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<KevyDbHandle> Function()>>(
        'kevy_open_mem',
      );
  late final _kevy_open_mem = _kevy_open_memPtr
      .asFunction<ffi.Pointer<KevyDbHandle> Function()>();

  /// Close the store. The handle must not be used afterwards.
  void kevy_close(ffi.Pointer<KevyDbHandle> db) {
    return _kevy_close(db);
  }

  late final _kevy_closePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<KevyDbHandle>)>>(
        'kevy_close',
      );
  late final _kevy_close = _kevy_closePtr
      .asFunction<void Function(ffi.Pointer<KevyDbHandle>)>();

  /// Execute one command; argv[0] is the verb ("SET", "IDX.CREATE", …).
  /// Writes the RESP reply to *out. Returns 0 on success — note a protocol
  /// error (-ERR …) is still a successful call with a RESP error in *out.
  /// Non-zero = the call itself was misused; *out is empty, do not free.
  int kevy_cmd(
    ffi.Pointer<KevyDbHandle> db,
    int argc,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> argv,
    ffi.Pointer<ffi.Size> argv_len,
    ffi.Pointer<KevyBuf> out,
  ) {
    return _kevy_cmd(db, argc, argv, argv_len, out);
  }

  late final _kevy_cmdPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<KevyDbHandle>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<KevyBuf>,
          )
        >
      >('kevy_cmd');
  late final _kevy_cmd = _kevy_cmdPtr
      .asFunction<
        int Function(
          ffi.Pointer<KevyDbHandle>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<KevyBuf>,
        )
      >();

  /// Scalar fast path — GET/SET without argv or RESP framing. The lane the
  /// mobile bindings' hot loop lives on. kevy_get: 1 hit / 0 miss / neg
  /// misuse; kevy_set: 0 ok / neg misuse (ttl_ms 0 = no TTL).
  int kevy_get(
    ffi.Pointer<KevyDbHandle> db,
    ffi.Pointer<ffi.Uint8> key,
    int key_len,
    ffi.Pointer<KevyBuf> out,
  ) {
    return _kevy_get(db, key, key_len, out);
  }

  late final _kevy_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<KevyDbHandle>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<KevyBuf>,
          )
        >
      >('kevy_get');
  late final _kevy_get = _kevy_getPtr
      .asFunction<
        int Function(
          ffi.Pointer<KevyDbHandle>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<KevyBuf>,
        )
      >();

  int kevy_set(
    ffi.Pointer<KevyDbHandle> db,
    ffi.Pointer<ffi.Uint8> key,
    int key_len,
    ffi.Pointer<ffi.Uint8> val,
    int val_len,
    int ttl_ms,
  ) {
    return _kevy_set(db, key, key_len, val, val_len, ttl_ms);
  }

  late final _kevy_setPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<KevyDbHandle>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Uint64,
          )
        >
      >('kevy_set');
  late final _kevy_set = _kevy_setPtr
      .asFunction<
        int Function(
          ffi.Pointer<KevyDbHandle>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
        )
      >();

  /// Zero-copy GET: a bulk value comes back as an Arc clone (refcount bump, no
  /// byte copy) whose bytes the returned buffer VIEWS — the analog of MMKV
  /// returning a view of its mmap page. In the out KevyBuf, ptr/len are the value
  /// view; cap is an OPAQUE owner handle. Free ONLY with kevy_buf_free_shared()
  /// (NOT kevy_buf_free). 1 hit / 0 miss / neg misuse.
  int kevy_get_shared(
    ffi.Pointer<KevyDbHandle> db,
    ffi.Pointer<ffi.Uint8> key,
    int key_len,
    ffi.Pointer<KevyBuf> out,
  ) {
    return _kevy_get_shared(db, key, key_len, out);
  }

  late final _kevy_get_sharedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<KevyDbHandle>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<KevyBuf>,
          )
        >
      >('kevy_get_shared');
  late final _kevy_get_shared = _kevy_get_sharedPtr
      .asFunction<
        int Function(
          ffi.Pointer<KevyDbHandle>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<KevyBuf>,
        )
      >();

  /// Free a KevyBuf from kevy_get_shared(): pass all three fields unchanged (cap
  /// is a tagged owner handle — an Arc for a bulk value or a Vec for a small
  /// one). Pairs 1:1 with kevy_get_shared; do NOT mix with kevy_buf_free.
  void kevy_buf_free_shared(ffi.Pointer<ffi.Uint8> ptr, int len, int cap) {
    return _kevy_buf_free_shared(ptr, len, cap);
  }

  late final _kevy_buf_free_sharedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Size, ffi.Size)
        >
      >('kevy_buf_free_shared');
  late final _kevy_buf_free_shared = _kevy_buf_free_sharedPtr
      .asFunction<void Function(ffi.Pointer<ffi.Uint8>, int, int)>();

  /// Free any KevyBuf returned by this library: pass its three fields
  /// unchanged. Scalars, not the struct by value — indirect struct passing
  /// (AArch64, >16 bytes) is beyond several FFI loaders. Null ptr = no-op.
  void kevy_buf_free(ffi.Pointer<ffi.Uint8> ptr, int len, int cap) {
    return _kevy_buf_free(ptr, len, cap);
  }

  late final _kevy_buf_freePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Size, ffi.Size)
        >
      >('kevy_buf_free');
  late final _kevy_buf_free = _kevy_buf_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Uint8>, int, int)>();

  /// Subscribe to one channel / one glob pattern. NULL on failure.
  ffi.Pointer<KevySubHandle> kevy_subscribe(
    ffi.Pointer<KevyDbHandle> db,
    ffi.Pointer<ffi.Uint8> chan,
    int chan_len,
  ) {
    return _kevy_subscribe(db, chan, chan_len);
  }

  late final _kevy_subscribePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<KevySubHandle> Function(
            ffi.Pointer<KevyDbHandle>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
          )
        >
      >('kevy_subscribe');
  late final _kevy_subscribe = _kevy_subscribePtr
      .asFunction<
        ffi.Pointer<KevySubHandle> Function(
          ffi.Pointer<KevyDbHandle>,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  ffi.Pointer<KevySubHandle> kevy_psubscribe(
    ffi.Pointer<KevyDbHandle> db,
    ffi.Pointer<ffi.Uint8> pat,
    int pat_len,
  ) {
    return _kevy_psubscribe(db, pat, pat_len);
  }

  late final _kevy_psubscribePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<KevySubHandle> Function(
            ffi.Pointer<KevyDbHandle>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
          )
        >
      >('kevy_psubscribe');
  late final _kevy_psubscribe = _kevy_psubscribePtr
      .asFunction<
        ffi.Pointer<KevySubHandle> Function(
          ffi.Pointer<KevyDbHandle>,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  /// Scalar publish — PUBLISH without the RESP round-trip (no argv packing, no
  /// reply buffer). Delivers to every in-process subscriber (direct + pattern)
  /// and returns the receiver count; -1 on misuse.
  int kevy_publish(
    ffi.Pointer<KevyDbHandle> db,
    ffi.Pointer<ffi.Uint8> chan,
    int chan_len,
    ffi.Pointer<ffi.Uint8> payload,
    int payload_len,
  ) {
    return _kevy_publish(db, chan, chan_len, payload, payload_len);
  }

  late final _kevy_publishPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(
            ffi.Pointer<KevyDbHandle>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
          )
        >
      >('kevy_publish');
  late final _kevy_publish = _kevy_publishPtr
      .asFunction<
        int Function(
          ffi.Pointer<KevyDbHandle>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  /// Fill *out with db's open verdict. 0 = ok, -1 = misuse.
  int kevy_open_report(
    ffi.Pointer<KevyDbHandle> db,
    ffi.Pointer<KevyOpenReport> out,
  ) {
    return _kevy_open_report(db, out);
  }

  late final _kevy_open_reportPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<KevyDbHandle>,
            ffi.Pointer<KevyOpenReport>,
          )
        >
      >('kevy_open_report');
  late final _kevy_open_report = _kevy_open_reportPtr
      .asFunction<
        int Function(ffi.Pointer<KevyDbHandle>, ffi.Pointer<KevyOpenReport>)
      >();

  /// kevy_open with explicit options: durable at dir when dir != NULL,
  /// in-memory when dir == NULL && dir_len == 0. NULL opts = kevy_open's
  /// defaults. NULL on failure.
  ffi.Pointer<KevyDbHandle> kevy_open_with(
    ffi.Pointer<ffi.Uint8> dir,
    int dir_len,
    ffi.Pointer<KevyOpenOptions> opts,
  ) {
    return _kevy_open_with(dir, dir_len, opts);
  }

  late final _kevy_open_withPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<KevyDbHandle> Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<KevyOpenOptions>,
          )
        >
      >('kevy_open_with');
  late final _kevy_open_with = _kevy_open_withPtr
      .asFunction<
        ffi.Pointer<KevyDbHandle> Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<KevyOpenOptions>,
        )
      >();

  /// Flush every shard's AOF (a REAL fsync), write the feed continuity
  /// marker, then refuse every later write (reads stay available) — the
  /// deterministic teardown: kevy_shutdown(db); exit(0). Idempotent.
  /// 0 = ok, -1 = misuse, -2 = I/O failure (store still usable; retry).
  int kevy_shutdown(ffi.Pointer<KevyDbHandle> db) {
    return _kevy_shutdown(db);
  }

  late final _kevy_shutdownPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<KevyDbHandle>)>
      >('kevy_shutdown');
  late final _kevy_shutdown = _kevy_shutdownPtr
      .asFunction<int Function(ffi.Pointer<KevyDbHandle>)>();

  /// Drain one pending frame without blocking.
  /// 1 = frame written to *out (RESP array: message / pmessage / acks);
  /// 0 = nothing queued; negative = misuse.
  int kevy_sub_next(ffi.Pointer<KevySubHandle> sub, ffi.Pointer<KevyBuf> out) {
    return _kevy_sub_next(sub, out);
  }

  late final _kevy_sub_nextPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<KevySubHandle>, ffi.Pointer<KevyBuf>)
        >
      >('kevy_sub_next');
  late final _kevy_sub_next = _kevy_sub_nextPtr
      .asFunction<
        int Function(ffi.Pointer<KevySubHandle>, ffi.Pointer<KevyBuf>)
      >();

  /// Block until one frame is queued or timeout_ms elapses (0 = wait forever).
  /// Parks the thread — no busy-poll — so a push-style poller can wait in the
  /// kernel instead of spinning kevy_sub_next.
  /// 1 = frame written to *out; 0 = timeout; negative = misuse / bus closed.
  int kevy_sub_wait(
    ffi.Pointer<KevySubHandle> sub,
    int timeout_ms,
    ffi.Pointer<KevyBuf> out,
  ) {
    return _kevy_sub_wait(sub, timeout_ms, out);
  }

  late final _kevy_sub_waitPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<KevySubHandle>,
            ffi.Uint64,
            ffi.Pointer<KevyBuf>,
          )
        >
      >('kevy_sub_wait');
  late final _kevy_sub_wait = _kevy_sub_waitPtr
      .asFunction<
        int Function(ffi.Pointer<KevySubHandle>, int, ffi.Pointer<KevyBuf>)
      >();

  /// Scalar drain — the raw message *payload* only, no RESP framing (the
  /// pub/sub analog of kevy_get). Skips control/ack frames, moves the payload
  /// into *out. For a known-channel push subscriber that only wants the bytes;
  /// the channel and message-vs-pmessage distinction are lost (a pattern
  /// subscriber that needs the channel keeps using kevy_sub_next).
  /// 1 = payload written to *out; 0 = nothing queued; negative = misuse.
  int kevy_sub_next_raw(
    ffi.Pointer<KevySubHandle> sub,
    ffi.Pointer<KevyBuf> out,
  ) {
    return _kevy_sub_next_raw(sub, out);
  }

  late final _kevy_sub_next_rawPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<KevySubHandle>, ffi.Pointer<KevyBuf>)
        >
      >('kevy_sub_next_raw');
  late final _kevy_sub_next_raw = _kevy_sub_next_rawPtr
      .asFunction<
        int Function(ffi.Pointer<KevySubHandle>, ffi.Pointer<KevyBuf>)
      >();

  /// Blocking kevy_sub_next_raw: parks up to timeout_ms (0 = wait forever).
  /// 1 = payload written to *out; 0 = timeout OR a control/ack frame was
  /// consumed (no payload) — re-wait; negative = misuse / bus closed.
  int kevy_sub_wait_raw(
    ffi.Pointer<KevySubHandle> sub,
    int timeout_ms,
    ffi.Pointer<KevyBuf> out,
  ) {
    return _kevy_sub_wait_raw(sub, timeout_ms, out);
  }

  late final _kevy_sub_wait_rawPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<KevySubHandle>,
            ffi.Uint64,
            ffi.Pointer<KevyBuf>,
          )
        >
      >('kevy_sub_wait_raw');
  late final _kevy_sub_wait_raw = _kevy_sub_wait_rawPtr
      .asFunction<
        int Function(ffi.Pointer<KevySubHandle>, int, ffi.Pointer<KevyBuf>)
      >();

  /// Close the subscription (unsubscribes everything it held).
  void kevy_sub_close(ffi.Pointer<KevySubHandle> sub) {
    return _kevy_sub_close(sub);
  }

  late final _kevy_sub_closePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<KevySubHandle>)>
      >('kevy_sub_close');
  late final _kevy_sub_close = _kevy_sub_closePtr
      .asFunction<void Function(ffi.Pointer<KevySubHandle>)>();

  /// Engine version, e.g. "4.0.0". Static string — do not free.
  ffi.Pointer<ffi.Char> kevy_version() {
    return _kevy_version();
  }

  late final _kevy_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'kevy_version',
      );
  late final _kevy_version = _kevy_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Runtime ABI version; compare against KEVY_ABI at startup.
  int kevy_abi() {
    return _kevy_abi();
  }

  late final _kevy_abiPtr = _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>(
    'kevy_abi',
  );
  late final _kevy_abi = _kevy_abiPtr.asFunction<int Function()>();
}

final class KevyDbHandle extends ffi.Opaque {}

final class KevySubHandle extends ffi.Opaque {}

/// A buffer owned by kevy. Never free() it — free it with the function paired
/// to the call that produced it (kevy_buf_free for most, kevy_buf_free_shared
/// for kevy_get_shared; passing a shared-lane buffer to kevy_buf_free corrupts
/// the heap). All three fields must reach that free untouched.
final class KevyBuf extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Size()
  external int len;

  @ffi.Size()
  external int cap;
}

/// The boot-replay verdict: what the open restored, and what it could not.
/// dropped_bytes > 0 or corrupt != 0 means the store recovered LESS than
/// its files held (the dropped region was quarantined next to the AOF as
/// aof-<id>.aof.corrupt-quarantine.<ts>) — surface it as a startup health
/// check.
final class KevyOpenReport extends ffi.Struct {
  @ffi.Uint64()
  external int replayed_commands;

  @ffi.Uint64()
  external int replayed_bytes;

  @ffi.Uint64()
  external int elapsed_ms;

  @ffi.Uint64()
  external int dropped_bytes;

  @ffi.Uint8()
  external int corrupt;

  @ffi.Uint32()
  external int quarantine_count;
}

/// Options for kevy_open_with. Start from KEVY_OPEN_OPTIONS_INIT (the
/// exact defaults kevy_open uses) and override what you need. rewrite_pct
/// 0 turns the growth rule off (as in Redis); rewrite_bytes /
/// rewrite_interval_secs are the absolute-size and staleness triggers
/// (0 = off). fsync: 0 everysec, 1 always, 2 no.
final class KevyOpenOptions extends ffi.Struct {
  @ffi.Uint8()
  external int fsync;

  @ffi.Uint32()
  external int shards;

  @ffi.Uint32()
  external int rewrite_pct;

  @ffi.Uint64()
  external int rewrite_min_size;

  @ffi.Uint64()
  external int rewrite_bytes;

  @ffi.Uint64()
  external int rewrite_interval_secs;
}

const int KEVY_ABI = 1;
